service: battle-royale

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: handler.main
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
